=== Yzoop/BSU/Web/lab7(lab2)/xsd_schema.xsd
<?xml version="1.0"?>
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.bsu.by"
        xmlns="http://www.bsu.by"
        elementFormDefault="qualified">

    <xs:simpleType name="Color" final="restriction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="green"/>
            <xs:enumeration value="red"/>
            <xs:enumeration value="yellow"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Medicine" abstract="true">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="price" type="xs:double"/>
            <xs:element name="manufactureDate" type="xs:date"/>
            <xs:element name="expirationDate" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ExternalMedicine" abstract="true">
        <xs:complexContent>
            <xs:extension base="Medicine">
                <xs:sequence>
                    <xs:element name="fluidityPercent" type="xs:double"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Gell">
        <xs:complexContent>
            <xs:extension base="ExternalMedicine">
                <xs:sequence>
                    <xs:element name="isCooling" type="xs:boolean"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Ointment">
        <xs:complexContent>
            <xs:extension base="ExternalMedicine">
                <xs:sequence>
                    <xs:element name="isWarming" type="xs:boolean"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="InternalMedicine" abstract="true">
        <xs:complexContent>
            <xs:extension base="Medicine">
                <xs:sequence>
                    <xs:element name="maxDailyDoseInMg" type="xs:double"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Antibiotic">
        <xs:complexContent>
            <xs:extension base="InternalMedicine">
                <xs:sequence>
                    <xs:element name="isRecipeRequired" type="xs:boolean"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Pill">
        <xs:complexContent>
            <xs:extension base="InternalMedicine">
                <xs:sequence>
                    <xs:element name="doseInMg" type="xs:double"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Syrup">
        <xs:complexContent>
            <xs:extension base="InternalMedicine">
                <xs:sequence>
                    <xs:element name="color" type="Color"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="MedicinesList">
        <xs:complexType>
            <xs:sequence>
                <xs:choice maxOccurs="unbounded" minOccurs="0">
                    <xs:element name="pill" type="Pill"/>
                    <xs:element name="antibiotic" type="Antibiotic"/>
                    <xs:element name="syrup" type="Syrup"/>
                    <xs:element name="ointment" type="Ointment"/>
                    <xs:element name="gell" type="Gell"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Yzoop/BSU/Web/lab7(lab2)/medicines.xml
<?xml version="1.0" encoding="UTF-8"?>
<MedicinesList
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.bsu.by"
        xsi:schemaLocation="http://www.bsu.by xsd_schema.xsd">

    <ointment>
        <name>Ointment1</name>
        <price>79.14</price>
        <manufactureDate>2002-09-24</manufactureDate>
        <expirationDate>2002-09-24</expirationDate>
        <fluidityPercent>50.5</fluidityPercent>
        <isWarming>true</isWarming>
    </ointment>

    <antibiotic>
        <name>Antibiotic4</name>
        <price>12.45</price>
        <manufactureDate>2002-09-24</manufactureDate>
        <expirationDate>2002-09-24</expirationDate>
        <maxDailyDoseInMg>5.5</maxDailyDoseInMg>
        <isRecipeRequired>false</isRecipeRequired>
    </antibiotic>

    <gell>
        <name>Gel5</name>
        <price>102.05</price>
        <manufactureDate>2002-09-24</manufactureDate>
        <expirationDate>2002-09-24</expirationDate>
        <fluidityPercent>2.4</fluidityPercent>
        <isCooling>false</isCooling>
    </gell>

    <pill>
        <name>Pill23</name>
        <price>98.79</price>
        <manufactureDate>2002-09-24</manufactureDate>
        <expirationDate>2002-09-24</expirationDate>
        <maxDailyDoseInMg>5.4</maxDailyDoseInMg>
        <doseInMg>2</doseInMg>
    </pill>

    <antibiotic>
        <name>Antibiotic2</name>
        <price>8.75</price>
        <manufactureDate>2002-09-24</manufactureDate>
        <expirationDate>2002-09-24</expirationDate>
        <maxDailyDoseInMg>50.5</maxDailyDoseInMg>
        <isRecipeRequired>true</isRecipeRequired>
    </antibiotic>

    <gell>
        <name>gel2</name>
        <price>65.79</price>
        <manufactureDate>2002-09-24</manufactureDate>
        <expirationDate>2002-09-24</expirationDate>
        <fluidityPercent>22.4</fluidityPercent>
        <isCooling>false</isCooling>
    </gell>

    <pill>
        <name>Pill43</name>
        <price>2.79</price>
        <manufactureDate>2002-09-24</manufactureDate>
        <expirationDate>2002-09-24</expirationDate>
        <maxDailyDoseInMg>2.4</maxDailyDoseInMg>
        <doseInMg>1</doseInMg>
    </pill>

    <syrup>
        <name>Syrup123</name>
        <price>58.79</price>
        <manufactureDate>2002-09-24</manufactureDate>
        <expirationDate>2002-09-24</expirationDate>
        <maxDailyDoseInMg>2</maxDailyDoseInMg>
        <color>yellow</color>
    </syrup>

    <syrup>
        <name>Syrup32</name>
        <price>65.79</price>
        <manufactureDate>2002-09-24</manufactureDate>
        <expirationDate>2002-09-24</expirationDate>
        <maxDailyDoseInMg>42.4</maxDailyDoseInMg>
        <color>red</color>
    </syrup>

    <ointment>
        <name>Ointment2</name>
        <price>124</price>
        <manufactureDate>2002-09-24</manufactureDate>
        <expirationDate>2002-09-24</expirationDate>
        <fluidityPercent>2.4</fluidityPercent>
        <isWarming>false</isWarming>
    </ointment>

</MedicinesList>
